#!/usr/bin/env bash
set -eou pipefail

cd "$(git rev-parse --show-toplevel)"

source scripts/env

./scripts/util/build tools

docker run "${COMMON_RUN_ARGS[@]}" \
           "${COMMON_RUN_UTIL_ARGS[@]}" \
           "${APP_NAME}-tools:latest" \
           "${@}"
